type: app
database: sqlite
language: ecr
model: granite

# list of tasks to be run by `amber watch`
watch:
  # NOTE: names that match crystal commands are special (e.g. run, spec)
  run:
    # commands will be joined with && (join them yourself if need || or ;)
    build_commands:
      - mkdir -p bin
      - crystal build ./src/combine.cr -o bin/combine
    run_commands:
      - bin/combine
    include:
      - ./config/**/*.cr
      - ./config/environments/*.yml
      - ./src/**/*.cr
      - ./src/**/*.ecr
      - ./src/locales/*.yml
    # exclude: # NOTE simplistic implementation: (1) enumerate all includes and excludes; (2) return (includes - excludes)
    #  - ./src/some_irrelevant_file.cr
  spec:
    run_commands:
      - AMBER_ENV=test crystal spec
    include:
      - ./spec/**/*.cr
