on:
  push:
  pull_request:
    branches: [main]
name: Run tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.13.1
      - name: Install shards
        run: shards install
        # Skipping format check and linting for the moment being.
      # - name: Lint
      #   run: ./bin/ameba
      # - name: Format
      #   run: crystal tool format --check
      - name: Run tests
        run: crystal spec --order=random
      - name: Build
        run: shards build
